### ISSUE TITLE
Dynmap Issue

### ISSUE THREAD

**Issue by bloggy** [MCTCP/TerrainControl#395]
I get these errors all the time in the console:

http://pastebin.com/gQPsVuqk

Are you able to fix it?

I am on latest Paper Spigot 1.9 Dev Build + Latest Terrain Control + Latest Dynmap

**Comment by rutgerkok** [comment]
Are you sure you are on the latest TerrainControl build? This bug should be fixed in build 121.

**Comment by bloggy** [comment]
I am sure that I have the latest build. I have build #124 on my server and the errors are still there:

http://pastebin.com/JVEfXUCi

**Comment by rutgerkok** [comment]
Hmm, so that means the bug wasn't fixed properly. Then I'll need some way to reproduce this.

Do you know what the exact name of the biome "MONOLITOUTER" is? (So in proper case, with spaces, etc., for example "Monolit Outer") Then I can create a biome with that name, and see if I also get the crash.

**Comment by bloggy** [comment]
I have uploaded the files you may need to reproduce:

This is the monolitouter file from my directory (plugins\TerrainControl\worlds\Lyria\WorldBiomes)
https://www.dropbox.com/s/39l6f5hxkwwts0p/monolitouter.bc?dl=0

And here is the worldconfig file:
https://www.dropbox.com/s/ihoz4hyi4dt3w2u/WorldConfig.ini?dl=0
from directory: plugins\TerrainControl\worlds\Lyria

Hope this helps! Let me know if I can help any further!

**Comment by bloggy** [comment]
Any update on this? Let me know if I can be of any help for you.

**Comment by rutgerkok** [comment]
I think I have now fixed the issue. Monolitouter is a so-called virtual biome. (It has ReplaceToBiomeName: Forest, so Monolitouter is never saved to the map files.) Dynmap should now hopefully be able to cope with this biome.

**Comment by bloggy** [comment]
Nice, I wait for the next dev build then and test it again!

**Comment by rutgerkok** [comment]
It should work for all biomes with a ReplaceToBiomeName value.

As the build server is not working anymore (Forge for 1.9 requires an update to the server) you can download a build here:

https://dl.dropboxusercontent.com/u/23288978/terraincontrol/TerrainControl.jar

**Comment by bloggy** [comment]
I will test it - thanks for your help! Really appreciate it! It's an awesome plugin :-)

**Comment by bloggy** [comment]
Console errors are not showing up anymore but unfortunately dynmap still does not render anything. I have tested it on different servers. There must be still an issue. Did it render for you?
