### ISSUE TITLE
Build #152 - Random Rotation not working

### ISSUE THREAD

**Issue by Robanaan** [MCTCP/TerrainControl#439]
Hello.

All my bo3's are facing the same direction despite rotaterandomly being set to true. 

Settings of an example bo3 here: http://pastebin.com/uaUffyrf

I think this came with the #152 build because I saw a change that had to do with rotation.

**Comment by rutgerkok** [comment]
Thanks, this should be fixed in the next build.

**Comment by Robanaan** [comment]
I compiled the updated source, but it doesn't seem to fix the issue. Did it work for you when you tested it or did you just assume it had to be fixed. If it worked for you, what could I be doing wrong?

**Comment by rutgerkok** [comment]
I used a very simple test BO3 (three torches):

![image](https://cloud.githubusercontent.com/assets/1462188/16741510/c8f379f6-47a3-11e6-9abd-b4c41a03428f.png)

I used [this build](http://build.mctcp.com/job/TerrainControl%20-%20Master%20-%20Gradle/154/default/).

**Comment by Robanaan** [comment]
That's really odd. Could it be that my bo3's are trees? 

![untitled](https://cloud.githubusercontent.com/assets/20384119/16742983/82c3da78-47aa-11e6-8829-9c6e40521e6d.png)

My config files would auto update since they are on WriteAll, right? I'll try to do it with a clean installation now though, just to check.

**Comment by rutgerkok** [comment]
So you mean spawned using `Tree(...)` instead of `CustomObject(...)`? I haven't tested that yet, I will do that tomorrow.

**Comment by Robanaan** [comment]
Yes, that's what I mean. Okay, see you tomorrow then.

**Comment by rutgerkok** [comment]
And it should now be fixed for `Tree(...)` too in [build 155](http://build.mctcp.com/job/TerrainControl%20-%20Master%20-%20Gradle/155/default/).

**Comment by Robanaan** [comment]
Yes, it works! Thanks.
